title: icyleaf
theme: nicesima
languageCode: zh
defaultContentLanguage: zh
disableHugoGeneratorInject: true
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true
paginate: 20

canonifyURLs: true

pygmentsUseClasses: true # 使用自定义的代码高亮样式
markup:
  highlight:
    codeFences: true
    anchorLineNos: false
    guessSyntax: false
    hl_Lines:
    lineAnchors:
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: tomorrow-night
    tabWidth: 4


params:
  # global settings
  home_mode: posts
  author: icyleaf
  avatar: images/icyleaf-icon.png
  description: 日常写代码热爱户外的梦想家
  subtitle: 你好，我是 icyleaf
  since: 2005
  mark: 🍺
  hideHUGOSupport: true
  hidePermalink: true
  googleAnalyticsUserID: UA-2570916-5
  googleAnalyticsCloudflareWorker: https://cfga.icyleaf.com

  # comment system
  disqusShortname: icyleaf

  socials:
    - name: github
      link: https://github.com/icyleaf
    - name: twitter
      link: https://twitter.com/icyleaf
    - name: facebook
      link: https://www.facebook.com/icyleaf
    - name: linkedin
      link: https://www.linkedin.com/in/icyleaf
    - name: instagram
      link: https://www.instagram.com/icyleaf/
    - name: douban
      link: https://www.douban.com/people/icyleaf

  # posts settings
  toc: true # 是否开启目录

permalinks:
  posts: /:year/:month/:slug
  page: /:filename

# disable all taxnomies
taxonomies:

# using process image in figure shortcode
assetDir: static

menu:
  main:
    - name: About
      weight: 50
      identifier: about
      url: /about
    - name: Feed
      weight: 100
      identifier: feed
      url: /index.xml
